services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./myapp:/app/myapp
      - /app/myapp/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    stdin_open: true
    tty: true